version: "2.4"

services:
  db:
    container_name: db # use this hostname at config/dev.exs
    image: postgres:alpine
    restart: always
    cpu_count: 1
    cpus: 0.5
    cpu_percent: 30
    mem_reservation: 256m
    mem_limit: 256m
    env_file: .env
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    cpu_count: 1
    cpus: 0.5
    cpu_percent: 30
    mem_reservation: 256m
    mem_limit: 256m
    tty: true
    volumes:
      - ./app:/home/elixiruser/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    cpu_count: 1
    cpus: 0.5
    cpu_percent: 30
    mem_reservation: 256m
    mem_limit: 256m
    env_file: .env
    ports:
      - "5555:80"
    depends_on:
      - db
