version: "3"

services:
  db:
    container_name: db # point this hostname at config/dev.exs
    image: postgres:alpine
    restart: always
    environment:
      # POSTGRES_DB: app_dev # config/dev.exs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
      # user: ${USER}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./app:/home/elixiruser/app
    ports:
      - "4000:4000"
    depends_on:
      - db
