version: "3"

services:
  phoenix:
    build: .
    volumes:
      - ./phoenix:/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
